# Generated by Django 5.2.7 on 2025-10-07 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ColetaFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roi/')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_coletas', to='registro.funcionario')),
            ],
        ),
        migrations.DeleteModel(
            name='coleta',
        ),
    ]
